# Generated by Django 5.0 on 2023-12-06 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_content', models.TextField(max_length=5000, verbose_name='Post Content')),
                ('views', models.IntegerField(default=0, verbose_name='Views')),
                ('owners_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.useraccount')),
            ],
            options={
                'ordering': ['owners_profile'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_title', models.CharField(max_length=250, verbose_name='Title')),
                ('comment_content', models.TextField(max_length=5000, verbose_name='Comment Content')),
                ('owners_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.useraccount')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.post')),
            ],
        ),
    ]
