# Generated by Django 5.0 on 2023-12-08 10:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('users', '0002_useraccount_profile_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['date_and_time_published']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['date_and_time_published']},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_title',
        ),
        migrations.AddField(
            model_name='comment',
            name='date_and_time_published',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date and time published'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='date_and_time_published',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date and time published'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('PR', 'Private'), ('PU', 'Public')], default=True, max_length=2, verbose_name='visibility'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_content',
            field=models.TextField(max_length=5000, verbose_name='comment content'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='owners_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.useraccount'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_content',
            field=models.TextField(max_length=5000, verbose_name='post content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='views',
            field=models.IntegerField(default=0, verbose_name='views'),
        ),
    ]
